# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os:
  - linux

r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

cache:
  directories:
    - /home/travis/ukbschemas-test-data/
  packages: true
