# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os:
  - linux
  - osx

r:
  - oldrel
  - release

warnings_are_errors: true

sudo: false

cache: packages
