# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os:
  - linux

r:
  - oldrel
  - release

warnings_are_errors: true

cache: packages

script:
  - R CMD build .
  - R CMD INSTALL *tar.gz
  - Rscript --vanilla ./tests/testthat.R
  - R CMD check *tar.gz
  